version: "3"
services:
    pwnme:
        build: ./pwnme
        expose:
          - "1337"
        restart: always
    nginx:
      build: ./nginx
      depends_on:
        - pwnme
      ports:
        - "4000:4000"
networks:
  default:
    driver: bridge
    name: pwnme