void st(uint8_t reg, uint16_t data);
void ld(uint8_t reg, uint16_t data);
void add(uint8_t reg, uint16_t data);
void br(uint8_t reg, uint16_t data);
void bz(uint8_t reg, uint16_t data);
void clr(uint8_t reg, uint16_t data);
void dec (uint8_t reg, uint16_t data);
void halt(uint8_t reg, uint16_t data);
void ei(uint8_t reg, uint16_t data);
void di(uint8_t reg, uint16_t data);